// noinspection JSUnusedGlobalSymbols,SpellCheckingInspection

import { v4 as uuid } from "uuid";
import { Quiz } from "../interfaces/quiz.interfaces";
import { quizToDraft } from "../utils/quiz.utils";

export class Globals {
    static SAMPLE_QUIZ_LIST: Quiz[] = [
        {
            id: uuid(),
            question: "In which Italian city can you find the Colosseum?",
            options: ["Rome", "Venice", "Florence", "Milan"],
            answer: ["Venice"],
        },
        {
            id: uuid(),
            question: "In the TV show New Girl, which actress plays Jessica Day?",
            options: ["Zooey Deschanel", "Zoe Saldana", "Zoe Kravitz", "Zoe Kazan"],
            answer: ["Zooey Deschanel"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest organ in the human body?",
            options: ["Liver", "Skin", "Heart", "Brain"],
            answer: ["Skin"],
        },
        {
            id: uuid(),
            question: "What is the tallest mammal?",
            options: ["Elephant", "Giraffe", "Horse", "Rhinoceros"],
            answer: ["Giraffe"],
        },
        {
            id: uuid(),
            question: "What is the name of the smallest planet in our solar system?",
            options: ["Jupiter", "Mars", "Mercury", "Venus"],
            answer: ["Mercury"],
        },
        {
            id: uuid(),
            question: "Which of the following animals can change its color?",
            options: ["Lion", "Chimpanzee", "Gorilla", "Chameleon"],
            answer: ["Chameleon"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest ocean on Earth?",
            options: ["Atlantic", "Indian", "Arctic", "Pacific"],
            answer: ["Pacific"],
        },
        {
            id: uuid(),
            question: "Which of the following animals has the longest lifespan?",
            options: ["Tortoise", "Elephant", "Lion", "Crocodile"],
            answer: ["Tortoise"],
        },
        {
            id: uuid(),
            question: "Which of the following is not a primary color?",
            options: ["Red", "Blue", "Green", "Yellow"],
            answer: ["Green"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest desert in the world?",
            options: ["Gobi", "Sahara", "Kalahari", "Mojave"],
            answer: ["Sahara"],
        },
        {
            id: uuid(),
            question: "What is the name of the second highest mountain in the world?",
            options: ["Mount Kilimanjaro", "Mount Everest", "K2", "Mount Denali"],
            answer: ["K2"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest bird in the world?",
            options: ["Ostrich", "Emu", "Penguin", "Albatross"],
            answer: ["Ostrich"],
        },
        {
            id: uuid(),
            question: "What is the name of the world's largest reef system?",
            options: ["Great Barrier Reef", "Red Sea Coral Reef", "Andros Coral Reef", "Mesoamerican Barrier Reef"],
            answer: ["Great Barrier Reef"],
        },
        {
            id: uuid(),
            question: "What is the name of the longest river in Africa?",
            options: ["Nile", "Congo", "Zambezi", "Niger"],
            answer: ["Nile"],
        },
        {
            id: uuid(),
            question: "Which of the following animals has the highest body temperature?",
            options: ["Horse", "Lion", "Elephant", "Bird"],
            answer: ["Bird"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest rodent in the world?",
            options: ["Gopher", "Hamster", "Capybara", "Beaver"],
            answer: ["Capybara"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest mammal in the world?",
            options: ["Elephant", "Hippopotamus", "Whale", "Giraffe"],
            answer: ["Whale"],
        },
        {
            id: uuid(),
            question: "What is the name of the smallest country in the world?",
            options: ["Vatican City", "Monaco", "Nauru", "San Marino"],
            answer: ["Vatican City"],
        },
        {
            id: uuid(),
            question: "Which of the following animals is not a mammal?",
            options: ["Kangaroo", "Platypus", "Shark", "Polar Bear"],
            answer: ["Shark"],
        },
        {
            id: uuid(),
            question: "What is the name of the highest mountain in Africa?",
            options: ["Mount Everest", "Mount Kilimanjaro", "Mount Denali", "Mount Aconcagua"],
            answer: ["Mount Kilimanjaro"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest reptile in the world?",
            options: ["Crocodile", "Turtle", "Lizard", "Snake"],
            answer: ["Crocodile"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest waterfall in the world?",
            options: ["Niagara Falls", "Angel Falls", "Iguazu Falls", "Victoria Falls"],
            answer: ["Victoria Falls"],
        },
        {
            id: uuid(),
            question: "Which of the following countries is not in Europe?",
            options: ["France", "Spain", "Russia", "Mexico"],
            answer: ["Mexico"],
        },
        {
            id: uuid(),
            question: "What is the name of the world's largest island?",
            options: ["Greenland", "Australia", "Iceland", "Madagascar"],
            answer: ["Greenland"],
        },
        {
            id: uuid(),
            question: "Which of the following planets is closest to the Sun?",
            options: ["Venus", "Earth", "Mars", "Mercury"],
            answer: ["Mercury"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest freshwater lake in the world?",
            options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"],
            answer: ["Lake Superior"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest bird of prey?",
            options: ["Eagle", "Falcon", "Owl", "Vulture"],
            answer: ["Vulture"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest carnivorous marsupial?",
            options: ["Kangaroo", "Wombat", "Koala", "Tasmanian Devil"],
            answer: ["Tasmanian Devil"],
        },
        {
            id: uuid(),
            question: "Which of the following is not a type of cloud?",
            options: ["Cumulus", "Stratus", "Nimbus", "Tsunami"],
            answer: ["Tsunami"],
        },
        {
            id: uuid(),
            question: "What is the name of the highest mountain in North America?",
            options: ["Mount McKinley", "Mount Kilimanjaro", "Mount Everest", "Mount Elbrus"],
            answer: ["Mount McKinley"],
        },
        {
            id: uuid(),
            question: "Which of the following is the smallest continent by land area?",
            options: ["Asia", "Australia", "Europe", "South America"],
            answer: ["Australia"],
        },
        {
            id: uuid(),
            question: "What is the name of the longest river in the world?",
            options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
            answer: ["Nile"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest fish in the world?",
            options: ["Blue Whale", "Hammerhead Shark", "Great White Shark", "Whale Shark"],
            answer: ["Whale Shark"],
        },
        {
            id: uuid(),
            question: "What is the name of the smallest planet in the Solar System?",
            options: ["Jupiter", "Mars", "Mercury", "Venus"],
            answer: ["Mercury"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest tree species in the world?",
            options: ["Sequoia", "Banyan", "Oak", "Maple"],
            answer: ["Sequoia"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest continent by land area?",
            options: ["Asia", "Australia", "Europe", "South America"],
            answer: ["Asia"],
        },
        {
            id: uuid(),
            question: "Which of the following animals is not a mammal?",
            options: ["Kangaroo", "Platypus", "Shark", "Polar Bear"],
            answer: ["Shark"],
        },
        {
            id: uuid(),
            question: "What is the name of the highest mountain in Africa?",
            options: ["Mount Everest", "Mount Kilimanjaro", "Mount Denali", "Mount Aconcagua"],
            answer: ["Mount Kilimanjaro"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest reptile in the world?",
            options: ["Crocodile", "Turtle", "Lizard", "Snake"],
            answer: ["Crocodile"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest waterfall in the world?",
            options: ["Niagara Falls", "Angel Falls", "Iguazu Falls", "Victoria Falls"],
            answer: ["Victoria Falls"],
        },
        {
            id: uuid(),
            question: "Which of the following countries is not in Europe?",
            options: ["France", "Spain", "Russia", "Mexico"],
            answer: ["Mexico"],
        },
        {
            id: uuid(),
            question: "What is the name of the world's largest island?",
            options: ["Greenland", "Australia", "Iceland", "Madagascar"],
            answer: ["Greenland"],
        },
        {
            id: uuid(),
            question: "Which of the following planets is closest to the Sun?",
            options: ["Venus", "Earth", "Mars", "Mercury"],
            answer: ["Mercury"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest freshwater lake in the world?",
            options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"],
            answer: ["Lake Superior"],
        },
        {
            id: uuid(),
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest bird of prey?",
            options: ["Eagle", "Falcon", "Owl", "Vulture"],
            answer: ["Vulture"],
        },
        {
            id: uuid(),
            question: "What is the name of the largest carnivorous marsupial?",
            options: ["Kangaroo", "Wombat", "Koala", "Tasmanian Devil"],
            answer: ["Tasmanian Devil"],
        },
        {
            id: uuid(),
            question: "Which of the following is not a type of cloud?",
            options: ["Cumulus", "Stratus", "Nimbus", "Tsunami"],
            answer: ["Tsunami"],
        },
    ];

    static SAMPLE_QUIZ_DRAFT_LIST = Globals.SAMPLE_QUIZ_LIST.map(quizToDraft);

    static SAMPLE_QUIZ_LIST_STATIC_IDS = [
        {
            id: "918d86d2-4940-45e6-8b2e-3bd3fc08bd84",
            question: "In which Italian city can you find the Colosseum?",
            options: ["Rome", "Venice", "Florence", "Milan"],
            answer: ["Venice"],
            heading: "Question 1",
        },
        {
            id: "028cbad5-210c-4d1b-8963-910773a634e0",
            question: "In the TV show New Girl, which actress plays Jessica Day?",
            options: ["Zooey Deschanel", "Zoe Saldana", "Zoe Kravitz", "Zoe Kazan"],
            answer: ["Zooey Deschanel"],
            heading: "Question 2",
        },
        {
            id: "74abe630-0bff-4e7d-9b84-ae00b0a0f4a3",
            question: "Which of the following is the largest organ in the human body?",
            options: ["Liver", "Skin", "Heart", "Brain"],
            answer: ["Skin"],
            heading: "Question 3",
        },
        {
            id: "cb1f7b53-d8cd-4e42-af3a-6365d406ce4f",
            question: "What is the tallest mammal?",
            options: ["Elephant", "Giraffe", "Horse", "Rhinoceros"],
            answer: ["Giraffe"],
            heading: "Question 4",
        },
        {
            id: "f1a05cff-2bed-4eae-af32-59e8f977b606",
            question: "What is the name of the smallest planet in our solar system?",
            options: ["Jupiter", "Mars", "Mercury", "Venus"],
            answer: ["Mercury"],
            heading: "Question 5",
        },
        {
            id: "b9d635d0-64c3-4b85-b823-9f4f14bda04b",
            question: "Which of the following animals can change its color?",
            options: ["Lion", "Chimpanzee", "Gorilla", "Chameleon"],
            answer: ["Chameleon"],
            heading: "Question 6",
        },
        {
            id: "662abd14-dc48-4ed5-af12-0411db5a24a7",
            question: "What is the name of the largest ocean on Earth?",
            options: ["Atlantic", "Indian", "Arctic", "Pacific"],
            answer: ["Pacific"],
            heading: "Question 7",
        },
        {
            id: "5a09853e-20dc-48f6-b3ed-296b4c9e19e1",
            question: "Which of the following animals has the longest lifespan?",
            options: ["Tortoise", "Elephant", "Lion", "Crocodile"],
            answer: ["Tortoise"],
            heading: "Question 8",
        },
        {
            id: "64c32f04-a415-4651-8802-f9316b1ca73b",
            question: "Which of the following is not a primary color?",
            options: ["Red", "Blue", "Green", "Yellow"],
            answer: ["Green"],
            heading: "Question 9",
        },
        {
            id: "e047dff0-312a-4bd8-a859-def999b746b1",
            question: "What is the name of the largest desert in the world?",
            options: ["Gobi", "Sahara", "Kalahari", "Mojave"],
            answer: ["Sahara"],
            heading: "Question 10",
        },
        {
            id: "cb06b7bb-7640-487c-bba9-5e88f5a6f16b",
            question: "What is the name of the second highest mountain in the world?",
            options: ["Mount Kilimanjaro", "Mount Everest", "K2", "Mount Denali"],
            answer: ["K2"],
            heading: "Question 11",
        },
        {
            id: "c7b97cc6-2388-4c86-8cf5-baa07c038700",
            question: "Which of the following is the largest bird in the world?",
            options: ["Ostrich", "Emu", "Penguin", "Albatross"],
            answer: ["Ostrich"],
            heading: "Question 12",
        },
        {
            id: "fd6a747c-803c-457a-ab26-9492782cd70a",
            question: "What is the name of the world's largest reef system?",
            options: ["Great Barrier Reef", "Red Sea Coral Reef", "Andros Coral Reef", "Mesoamerican Barrier Reef"],
            answer: ["Great Barrier Reef"],
            heading: "Question 13",
        },
        {
            id: "39ab2314-8a1e-4623-8331-1c002a6c4ef3",
            question: "What is the name of the longest river in Africa?",
            options: ["Nile", "Congo", "Zambezi", "Niger"],
            answer: ["Nile"],
            heading: "Question 14",
        },
        {
            id: "f5d48651-1e62-4705-9e41-882070f1c53c",
            question: "Which of the following animals has the highest body temperature?",
            options: ["Horse", "Lion", "Elephant", "Bird"],
            answer: ["Bird"],
            heading: "Question 15",
        },
        {
            id: "a12338fc-aec9-45c5-8ea2-0d3e4c17c89e",
            question: "What is the name of the largest rodent in the world?",
            options: ["Gopher", "Hamster", "Capybara", "Beaver"],
            answer: ["Capybara"],
            heading: "Question 16",
        },
        {
            id: "a712e7d7-dfb7-45e1-b8e6-3f1293049072",
            question: "Which of the following is the largest mammal in the world?",
            options: ["Elephant", "Hippopotamus", "Whale", "Giraffe"],
            answer: ["Whale"],
            heading: "Question 17",
        },
        {
            id: "afb9154c-86e9-4aa5-b5ef-3808d19674f4",
            question: "What is the name of the smallest country in the world?",
            options: ["Vatican City", "Monaco", "Nauru", "San Marino"],
            answer: ["Vatican City"],
            heading: "Question 18",
        },
        {
            id: "f7c96dbb-aed9-4101-997f-44e8335a08dd",
            question: "Which of the following animals is not a mammal?",
            options: ["Kangaroo", "Platypus", "Shark", "Polar Bear"],
            answer: ["Shark"],
            heading: "Question 19",
        },
        {
            id: "28146b22-4ca1-4565-9616-280ba2634f2b",
            question: "What is the name of the highest mountain in Africa?",
            options: ["Mount Everest", "Mount Kilimanjaro", "Mount Denali", "Mount Aconcagua"],
            answer: ["Mount Kilimanjaro"],
            heading: "Question 20",
        },
        {
            id: "575a6fd7-ef9f-49d3-990d-0c1a023459da",
            question: "Which of the following is the largest reptile in the world?",
            options: ["Crocodile", "Turtle", "Lizard", "Snake"],
            answer: ["Crocodile"],
            heading: "Question 21",
        },
        {
            id: "e1bc7f8d-2a57-4e1a-9c93-cf61b42a5b99",
            question: "What is the name of the largest waterfall in the world?",
            options: ["Niagara Falls", "Angel Falls", "Iguazu Falls", "Victoria Falls"],
            answer: ["Victoria Falls"],
            heading: "Question 22",
        },
        {
            id: "45da7af4-64e4-4305-8a76-c3083c0f5a4c",
            question: "Which of the following countries is not in Europe?",
            options: ["France", "Spain", "Russia", "Mexico"],
            answer: ["Mexico"],
            heading: "Question 23",
        },
        {
            id: "094d3476-0611-4659-b740-6364f3118750",
            question: "What is the name of the world's largest island?",
            options: ["Greenland", "Australia", "Iceland", "Madagascar"],
            answer: ["Greenland"],
            heading: "Question 24",
        },
        {
            id: "12948457-c791-42bc-8ced-44476a1eb973",
            question: "Which of the following planets is closest to the Sun?",
            options: ["Venus", "Earth", "Mars", "Mercury"],
            answer: ["Mercury"],
            heading: "Question 25",
        },
        {
            id: "2a63bf43-7987-48ad-8933-aeeee2f01d1f",
            question: "What is the name of the largest freshwater lake in the world?",
            options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"],
            answer: ["Lake Superior"],
            heading: "Question 26",
        },
        {
            id: "303b9ab4-7280-4bc4-9558-63e2095c96b2",
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
            heading: "Question 27",
        },
        {
            id: "2c5833cf-f2a3-4a57-83a2-44fba98c82c2",
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
            heading: "Question 28",
        },
        {
            id: "13f8e7fe-4694-41ac-a84d-77c842d21ea6",
            question: "What is the name of the largest bird of prey?",
            options: ["Eagle", "Falcon", "Owl", "Vulture"],
            answer: ["Vulture"],
            heading: "Question 29",
        },
        {
            id: "b2751dd7-c02a-4925-8195-f49e3ddab5f4",
            question: "What is the name of the largest carnivorous marsupial?",
            options: ["Kangaroo", "Wombat", "Koala", "Tasmanian Devil"],
            answer: ["Tasmanian Devil"],
            heading: "Question 30",
        },
        {
            id: "e734f5c0-7f6f-438c-97f0-68b2fb1d165c",
            question: "Which of the following is not a type of cloud?",
            options: ["Cumulus", "Stratus", "Nimbus", "Tsunami"],
            answer: ["Tsunami"],
            heading: "Question 31",
        },
        {
            id: "3d7d4198-836d-42de-a6c7-94332f8d49f7",
            question: "What is the name of the highest mountain in North America?",
            options: ["Mount McKinley", "Mount Kilimanjaro", "Mount Everest", "Mount Elbrus"],
            answer: ["Mount McKinley"],
            heading: "Question 32",
        },
        {
            id: "202d0847-daff-4ed2-a87b-bde29e83e9dd",
            question: "Which of the following is the smallest continent by land area?",
            options: ["Asia", "Australia", "Europe", "South America"],
            answer: ["Australia"],
            heading: "Question 33",
        },
        {
            id: "fbdd6b24-13b2-4067-a363-10f3e16af0cd",
            question: "What is the name of the longest river in the world?",
            options: ["Nile", "Amazon", "Yangtze", "Mississippi"],
            answer: ["Nile"],
            heading: "Question 34",
        },
        {
            id: "13bada01-51b8-4906-8db0-5cc846188d90",
            question: "Which of the following is the largest fish in the world?",
            options: ["Blue Whale", "Hammerhead Shark", "Great White Shark", "Whale Shark"],
            answer: ["Whale Shark"],
            heading: "Question 35",
        },
        {
            id: "ae2a1bfe-d033-4a5f-87b3-66782b38eda0",
            question: "What is the name of the smallest planet in the Solar System?",
            options: ["Jupiter", "Mars", "Mercury", "Venus"],
            answer: ["Mercury"],
            heading: "Question 36",
        },
        {
            id: "1a268fce-53dc-4cda-8251-e10839b57730",
            question: "Which of the following is the largest tree species in the world?",
            options: ["Sequoia", "Banyan", "Oak", "Maple"],
            answer: ["Sequoia"],
            heading: "Question 37",
        },
        {
            id: "0e25d0b2-a3c4-4ad2-8d14-c3be22ed4baa",
            question: "What is the name of the largest continent by land area?",
            options: ["Asia", "Australia", "Europe", "South America"],
            answer: ["Asia"],
            heading: "Question 38",
        },
        {
            id: "b7676edd-8bf7-43a2-84ea-3b8a1efb10c5",
            question: "Which of the following animals is not a mammal?",
            options: ["Kangaroo", "Platypus", "Shark", "Polar Bear"],
            answer: ["Shark"],
            heading: "Question 39",
        },
        {
            id: "450c400e-d55a-4fa7-994b-b21bac2e0188",
            question: "What is the name of the highest mountain in Africa?",
            options: ["Mount Everest", "Mount Kilimanjaro", "Mount Denali", "Mount Aconcagua"],
            answer: ["Mount Kilimanjaro"],
            heading: "Question 40",
        },
        {
            id: "46fefabb-2089-41ed-bf81-cbed83ff85ab",
            question: "Which of the following is the largest reptile in the world?",
            options: ["Crocodile", "Turtle", "Lizard", "Snake"],
            answer: ["Crocodile"],
            heading: "Question 41",
        },
        {
            id: "d156c7c6-f104-45aa-af7f-7d52e373e546",
            question: "What is the name of the largest waterfall in the world?",
            options: ["Niagara Falls", "Angel Falls", "Iguazu Falls", "Victoria Falls"],
            answer: ["Victoria Falls"],
            heading: "Question 42",
        },
        {
            id: "da740525-71f2-4293-96a2-7bc76322829c",
            question: "Which of the following countries is not in Europe?",
            options: ["France", "Spain", "Russia", "Mexico"],
            answer: ["Mexico"],
            heading: "Question 43",
        },
        {
            id: "83e1226f-0494-4838-a9ec-50bd3ce922f5",
            question: "What is the name of the world's largest island?",
            options: ["Greenland", "Australia", "Iceland", "Madagascar"],
            answer: ["Greenland"],
            heading: "Question 44",
        },
        {
            id: "f6c7ed39-dd01-4319-8f8b-56e602f27658",
            question: "Which of the following planets is closest to the Sun?",
            options: ["Venus", "Earth", "Mars", "Mercury"],
            answer: ["Mercury"],
            heading: "Question 45",
        },
        {
            id: "721e6903-b4a6-49bf-9978-f7087256596e",
            question: "What is the name of the largest freshwater lake in the world?",
            options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"],
            answer: ["Lake Superior"],
            heading: "Question 46",
        },
        {
            id: "d3c59332-d3f6-48bb-b9e6-79d490d51f17",
            question: "Which of the following is the largest moon in the Solar System?",
            options: ["Ganymede", "Titan", "Europa", "Callisto"],
            answer: ["Ganymede"],
            heading: "Question 47",
        },
        {
            id: "93ef3cce-63a3-4d36-9152-ba47154f7aef",
            question: "What is the name of the largest bird of prey?",
            options: ["Eagle", "Falcon", "Owl", "Vulture"],
            answer: ["Vulture"],
            heading: "Question 48",
        },
        {
            id: "68e24e13-ea65-4c54-a578-f99bf1fec8e6",
            question: "What is the name of the largest carnivorous marsupial?",
            options: ["Kangaroo", "Wombat", "Koala", "Tasmanian Devil"],
            answer: ["Tasmanian Devil"],
            heading: "Question 49",
        },
        {
            id: "3fe808c7-e8c1-46e6-a078-b71b07252391",
            question: "Which of the following is not a type of cloud?",
            options: ["Cumulus", "Stratus", "Nimbus", "Tsunami"],
            answer: ["Tsunami"],
            heading: "Question 50",
        },
    ];
}
